# Generated by Django 4.2.6 on 2023-10-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_category_options_domain_is_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain.category'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
