# Generated by Django 4.2.6 on 2023-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_alter_domain_category_alter_domain_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
