# Generated by Django 4.2.6 on 2023-10-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_domain_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='employee/photos/%Y/%m/%d/')),
                ('email', models.EmailField(max_length=254)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
