# Generated by Django 4.2.6 on 2023-10-08 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_alter_domain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
